docker rm getfoodfaster_postgres
docker rm getfoodfaster_pgadmin
docker rm getfoodfaster_cloudbeaver

docker volume rm appdreactotgetfoodfaster_cloudbeaver-data
docker volume rm appdreactotgetfoodfaster_pgadmin-data
docker volume rm appdreactotgetfoodfaster_postgres-data